name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.0" # 使用している Go のバージョンに合わせて変更

      - name: Build the Go binary from cmd
        run: |
          go mod download
          CGO_ENABLED=0 go build -a -installsuffix cgo -o sagaicle ./cmd

      - name: Copy binary to VPS
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "sagaicle"
          target: "/home/miray/sushigon"

      - name: Copy init.sql to VPS
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "init.sql"
          target: "/home/miray/sushigon"

      - name: Run remote commands on VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/miray/sushigon/
            chmod +x sagaicle
            systemctl --user restart sagaicle.service
